### ISSUE TITLE
Dataset for evaluation

### ISSUE THREAD

**Issue by ku2482** [astorfi/3D-convolutional-speaker-recognition#19]
Hi Astorfi,
I'm trying to train speaker recognition model with your model.
Since I'm a beginner at programming, I don't understand your code nicely.
For enrollment and evaluation phase, I just have to prepare the data (shape of (sample, 1, 80, 40))??
I read the paper and I don't know if I have to copy the data of single utterance to make the data (shape of (sample, 20, 80, 40)).

Also I prepare the data for development (shape of (97, 20, 80, 40)) using input_feature.py, but do I have to prepare the data (shape of (97, 80, 40, 20))??

Thank you very much.

**Comment by astorfi** [comment]
"I read the paper and I don't know if I have to copy the data of single utterance to make the data (shape of (sample, 20, 80, 40))": Answer: For evaluation, you need to copy.

"Also I prepare the data for development (shape of (97, 20, 80, 40)) using input_feature.py, but do I have to prepare the data (shape of (97, 80, 40, 20))??" Answer: The shape must be formed as it is mentioned in the paper and/or the default of this repository because the architecture is designed and adapted for the specific shape.

**Comment by ku2482** [comment]
Thank you for answering!!
Also I'm wondering whether "frame_length=0.025"in input_feature.py is correct??
I see the paper and it seems that "frame_length=0.02" is correct.

I made my own dataset using input_feature.py and training with it, but test accuracy never go up.
Do I have to make dataset with
`dataset = AudioDataset(files_path=args.file_path, audio_dir=args.audio_dir,
                           transform=Compose([CMVN(), Feature_Cube(cube_shape=(20, 80, 40), augmentation=True), ToOutput()]))
`
and dataset.__get_item__ for each index, is it right?? 

Sorry for bothering you.
Thank you very much!!
