### ISSUE TITLE
About voice/speaker verification task.

### ISSUE THREAD

**Issue by tailongnguyen** [astorfi/3D-convolutional-speaker-recognition#32]
Hi astorfi,
Thanks for such a great work. I want to ask you some questions, because I am quite in DL but new to speech field so please forgive me if I ask any dump question :D
1. What do you mean by 'input as stacked utterances', utterance here means a sentence, a word or something else?
2. How large should the dataset be (the number of different speakers, the number of samples) for the model to work well on voice verification task?

**Comment by astorfi** [comment]
@tailongnguyen 
Actually, in the beginning, it is not an easy problem to understand. So it is totally understandable.

1. It means by stacking differently spoken utterances (their associated features) the input is made.
2. The rule of thumb says the larger, the better.

Please refer to the associated paper for further details.
Thanks

**Comment by pranoot** [comment]
Hello @astorfi ,

I still have doubt about the dataset specification and the network. Can you please help me with the same.

Can you tell me how large the dataset network can handle so that it doesn't underfit and converges well (i.e number of speakers,  number of utterances per speaker ) ??

Thank you.
